global:
  scrape_interval: 15s # 默认 15s 采集一次
  external_labels:
    monitor: "go-paas-monitor"
scrape_configs:
  - job_name: 'base'
    scrape_interval: 5s # 覆盖默认值
    static_configs:
      - targets: ['192.168.1.108:9192']