version: '3.3'
services:
  # Consul 注册中心集群版本
  consul1:
    image: cap1573/consul
    container_name: node1
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
  consul2:
    image: cap1573/consul
    container_name: node2
    command: agent -server -bootstrap-expect=3 -node=node2 -retry-join=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  consul3:
    image: cap1573/consul
    container_name: node3
    command: agent -server -bootstrap-expect=3 -node=node3 -retry-join=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  # 添加对外暴露的端口，启动控制面板
  consul4:
    image: cap1573/consul
    container_name: node4
    command: agent -node=node4 -retry-join=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - "8500:8500"
    depends_on:
      - consul2
      - consul3
  # 数据库
  paas-mysql:
    image: cap1573/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      container_name: paas-mysql
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
  # 分布式链路追踪
  jaeger:
    image: cap1573/jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"